import { StyleSheet } from "react-native";
import { colors } from "../theme/colors";
import { spacing } from "../theme/spacing";
import { typography } from "../theme/typography";

// Enhanced button styles
const buttonStyles = {
  primary: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: spacing.borderRadius,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: spacing.shadowRadius,
    elevation: spacing.elevation,
  },
  primaryLarge: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: spacing.borderRadius,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: spacing.shadowRadius,
    elevation: spacing.elevation + 1,
  },
  danger: {
    backgroundColor: colors.danger,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: spacing.borderRadiusSmall,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: spacing.shadowRadiusSmall,
    elevation: spacing.elevationSmall,
  },
  success: {
    backgroundColor: colors.success,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: spacing.borderRadiusSmall,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: spacing.shadowRadiusSmall,
    elevation: spacing.elevationSmall,
  },
  secondary: {
    backgroundColor: colors.background,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: spacing.borderRadiusSmall,
    borderWidth: 1,
    borderColor: colors.border,
  },
  ghost: {
    backgroundColor: 'transparent',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: spacing.borderRadiusSmall,
    borderWidth: 1,
    borderColor: colors.primary,
  },
};

// Enhanced text styles
const textStyles = {
  title: typography.appTitle,
  heading: typography.sectionTitle,
  subheading: typography.taskTitle,
  body: typography.body,
  caption: typography.caption,
  small: typography.small,
  button: typography.button,
  buttonTextSmall: typography.buttonTextSmall,
  buttonTextTiny: typography.buttonTextTiny,
  link: {
    ...typography.button,
    color: colors.primary,
    textDecorationLine: 'underline' as const,
  },
};

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.headerPadding,
    paddingVertical: spacing.headerPadding,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
    shadowColor: colors.shadowLight,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: spacing.shadowRadiusSmall,
    elevation: spacing.elevationSmall,
  },
  title: typography.appTitle,
  addButton: buttonStyles.primaryLarge,
  addButtonText: typography.button,
  tasksContainer: {
    flex: 1,
  },
  sectionTitle: typography.sectionTitle,
  taskList: {
    flex: 1,
  },
  taskItem: {
    backgroundColor: colors.surface,
    padding: spacing.cardPadding,
    marginBottom: spacing.cardMargin,
    borderRadius: spacing.borderRadiusLarge,
    borderWidth: 1,
    borderColor: colors.borderLight,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: spacing.shadowRadius,
    elevation: spacing.elevation,
    width: '100%',
  },
  taskHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  taskTitle: {
    ...typography.taskTitle,
    color: colors.primary,
    padding: spacing.xs,
    textDecorationLine: 'underline',
  },
  deleteButton: {
    ...buttonStyles.danger,
    width: spacing.iconSize,
    height: spacing.iconSize,
    borderRadius: spacing.iconSize / 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteButtonText: {
    ...typography.button,
    fontSize: 18,
  },
  completeButton: buttonStyles.success,
  completeButtonText: typography.buttonTextSmall,
  taskDetails: typography.caption,
  taskActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.xs,
  },
  statusToggle: buttonStyles.ghost,
  taskStatus: {
    ...typography.buttonTextTiny,
    color: colors.primary,
  },
  emptyText: {
    ...typography.body,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: spacing.xl,
  },
  weeklyStats: {
    backgroundColor: colors.successLight,
    padding: spacing.sm,
    marginTop: spacing.sm,
    borderRadius: spacing.borderRadius,
    borderWidth: 1,
    borderColor: colors.success,
  },
  weeklyStatsTitle: typography.subheading,
  weeklyStatsText: typography.caption,
});

// Progress ring styles
export const progressStyles = StyleSheet.create({
  container: {
    backgroundColor: colors.surface,
    padding: 20,
    marginBottom: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.borderLight,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  title: textStyles.heading,
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  progressRing: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 3,
    borderColor: colors.borderLight,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  progressRingFill: {
    position: 'absolute',
    top: -3,
    left: -3,
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 3,
    borderColor: colors.success,
    borderTopColor: 'transparent',
    borderRightColor: 'transparent',
    transform: [{ rotate: '-90deg' }],
  },
  progressText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  progressDots: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginLeft: 16,
  },
  progressDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginHorizontal: 2,
  },
  progressDotFilled: {
    backgroundColor: colors.success,
  },
  progressDotEmpty: {
    backgroundColor: colors.borderLight,
  },
  progressStats: {
    fontSize: 14,
    color: colors.textSecondary,
    fontWeight: '500',
  },
});

export const addTaskStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  label: {
    ...textStyles.subheading,
    marginBottom: 12,
    color: colors.text,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    marginBottom: 20,
    backgroundColor: colors.surface,
    color: colors.text,
    shadowColor: colors.shadowLight,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  inputFocused: {
    borderColor: colors.primary,
    borderWidth: 2,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    gap: 8,
    flexWrap: 'wrap',
  },
  dateButton: {
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    backgroundColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.shadowLight,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  dateButtonText: {
    ...textStyles.body,
    color: colors.text,
  },
  frequencyButton: {
    backgroundColor: colors.background,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.shadowLight,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  frequencyButtonSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  frequencyButtonText: {
    ...textStyles.buttonTextSmall,
    color: colors.text,
  },
  frequencyButtonTextSelected: {
    color: colors.surface,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 32,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 6,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  cardTitle: {
    ...textStyles.title,
    marginBottom: 24,
    textAlign: 'center',
  },
  saveButton: buttonStyles.primaryLarge,
});
