import { StyleSheet, Dimensions } from "react-native";
import { colors } from "../theme/colors";
import { spacing } from "../theme/spacing";
import { typography } from "../theme/typography";

const buttonStyles = {
  primary: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: spacing.borderRadius,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: spacing.shadowRadius,
    elevation: spacing.elevation,
  },
  primaryLarge: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: spacing.borderRadius,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: spacing.shadowRadius,
    elevation: spacing.elevation + 1,
  },
  danger: {
    backgroundColor: colors.danger,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: spacing.borderRadiusSmall,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: spacing.shadowRadiusSmall,
    elevation: spacing.elevationSmall,
  },
  success: {
    backgroundColor: colors.success,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: spacing.borderRadiusSmall,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: spacing.shadowRadiusSmall,
    elevation: spacing.elevationSmall,
  },
  secondary: {
    backgroundColor: colors.background,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: spacing.borderRadiusSmall,
    borderWidth: 1,
    borderColor: colors.border,
  },
  ghost: {
    backgroundColor: 'transparent',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: spacing.borderRadiusSmall,
    borderWidth: 1,
    borderColor: colors.primary,
  },
};

const textStyles = {
  title: typography.appTitle,
  heading: typography.sectionTitle,
  subheading: typography.taskTitle,
  body: typography.body,
  caption: typography.caption,
  small: typography.small,
  button: typography.button,
  buttonTextSmall: typography.buttonTextSmall,
  buttonTextTiny: typography.buttonTextTiny,
  link: {
    ...typography.button,
    color: colors.primary,
    textDecorationLine: 'underline' as const,
  },
};

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screenWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    minHeight: Dimensions.get('window').height,
    paddingVertical: 20,
  },
  header: {
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.headerPadding,
    paddingVertical: spacing.headerPadding,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
    shadowColor: colors.shadowLight,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: spacing.shadowRadiusSmall,
    elevation: spacing.elevationSmall,
  },
  title: typography.appTitle,
  addButton: buttonStyles.primaryLarge,
  addButtonText: typography.button,
  tasksContainer: {
    flex: 1,
  },
  pageContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  sectionTitle: typography.sectionTitle,
  taskList: {
    flex: 1,
  },
  taskItem: {
    backgroundColor: colors.surface,
    padding: spacing.cardPadding,
    marginBottom: spacing.cardMargin,
    borderRadius: spacing.borderRadiusLarge,
    borderWidth: 1,
    borderColor: colors.borderLight,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: spacing.shadowRadius,
    elevation: spacing.elevation,
    width: '100%',
  },
  overdueTaskItem: {
    borderColor: colors.danger,
    borderWidth: 2,
  },
  taskHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  taskTitle: {
    ...typography.taskTitle,
    color: colors.primary,
    padding: spacing.xs,
    textDecorationLine: 'underline',
  },
  taskIcon: {
    fontSize: 32,
    marginRight: 12,
  },
  taskTagWarning: {
    backgroundColor: colors.warning,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    marginLeft: 8,
  },
  taskTagDanger: {
    backgroundColor: colors.danger,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    marginLeft: 8,
  },
  taskTagText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#000',
  },
  taskTagTextDanger: {
    fontSize: 10,
    fontWeight: '600',
    color: '#fff',
  },
  deleteButton: {
    ...buttonStyles.danger,
    width: spacing.iconSize,
    height: spacing.iconSize,
    borderRadius: spacing.iconSize / 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteButtonText: {
    ...typography.button,
    fontSize: 18,
  },
  completeButton: buttonStyles.success,
  completeButtonText: typography.buttonTextSmall,
  taskDetails: {
    marginBottom: 16,
  },
  taskDetailText: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 4,
  },
  taskDetailValue: {
    fontWeight: '600',
    color: colors.text,
  },
  taskActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.xs,
  },
  activeLabel: {
    backgroundColor: colors.success,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  activeLabelText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.surface,
  },
  statusToggle: buttonStyles.ghost,
  taskStatus: {
    ...typography.buttonTextTiny,
    color: colors.primary,
  },
  emptyText: {
    ...typography.body,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: spacing.xl,
  },
  sectionCard: {
    backgroundColor: '#f8f9fa',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerButton: {
    ...buttonStyles.primary,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
  },
  headerButtonText: {
    ...typography.button,
    color: colors.surface,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    minHeight: Dimensions.get('window').height,
  },
  loadingText: {
    fontSize: 16,
    color: '#666',
    marginTop: 20,
    textAlign: 'center',
  },
  debugBox: {
    backgroundColor: '#f0f0f0',
    padding: 10,
    margin: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  debugTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  debugText: {
    fontSize: 10,
  },
  dueTomorrowItem: {
    backgroundColor: colors.surface,
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  dueTomorrowTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.text,
    marginBottom: 4,
  },
  dueTomorrowSubtitle: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  weeklyStats: {
    backgroundColor: colors.successLight,
    padding: spacing.sm,
    marginTop: spacing.sm,
    borderRadius: spacing.borderRadius,
    borderWidth: 1,
    borderColor: colors.success,
  },
  weeklyStatsText: typography.caption,
  weeklyStatsValue: {
    fontWeight: '600',
    color: colors.text,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 400,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  modalSubtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    marginBottom: 24,
    textAlign: 'center',
  },
  modalButton: {
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 24,
    marginBottom: 12,
    alignItems: 'center',
  },
  modalButtonPrimary: {
    backgroundColor: colors.primary,
  },
  modalButtonSuccess: {
    backgroundColor: colors.success,
  },
  modalButtonDanger: {
    backgroundColor: colors.danger,
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.surface,
  },
  modalButtonDescription: {
    fontSize: 12,
    color: colors.surface,
    marginTop: 4,
    textAlign: 'center',
  },
});